import type { Metadata } from "next";
import { ReactLenis} from 'lenis/react'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root />
      <body
        className={`outfit antialiased bg-[#1f1f1f] px-[10px] sm:px-[50px]`}
      >
        {children}
      </body>
    </html>
  );
}
